### ISSUE TITLE
io

### ISSUE THREAD

**Issue by PencilCoder0E** [rusted-love/react-hooks#1]
fuck your fucking Russian mother

**Comment by rusted-love** [comment]
Such a funny Russian bot. Go cry.

**Comment by rusted-love** [comment]
@PencilCoder0E Сподіваюсь скоро ти сам відправишся на концерт Кобзона.

**Comment by rusted-love** [comment]
@PencilCoder0E  

1.  Цікаво, з чого ти це взяв що я росіянин.
2. Методи твоєї боротьби не ефективні. Вони дискредитують націю і викликають лише відразу в іноземних союзників. 
3. Замість того щоб витрачати час на такі речі краще займись розвитком українського бізнесу. Допомагай навичками програмування державі та військовому сектору
4. В решті решт популяризуй Україну серед міжнародних партнерів класними проектами. Це дуже допоможе репутації України на світовій арені. Значно більше ніж "спам ненависливими фразами".
5. Своїми фразами, де ти вживаєш багато разів слово "Russia" ти лише популяризуєш їхню країну, робиш її більш впізнаваною. Якщо хочеш зробити їм гірше, максимально уникай вживання назви країни-агрессора.

Перед тим як щось робити завжди думай яку користь чи негативний вплив це принесе. 
Якщо ти справді хочеш насолити росіянам, витісни їх з світового ринку своєю працею, щоб в їхню державу поступало менше коштів на ведення війни.

**Comment by rusted-love** [comment]
@PencilCoder0E А ще почисть весь цей бруд. (Я про назву країни-агресора.) 

<img width="1295" alt="Screenshot 2023-09-09 at 13 48 11" src="https://github.com/rusted-love/react-hooks/assets/32598874/7dbf7907-501d-432b-b29e-4de8adc903ad">
